name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - tinker
  pull_request:
    branches:
      - master
      - tinker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Checkout code
      uses: actions/checkout@v2

    - name: 6th_D
      if: github.ref == 'refs/heads/master'
      run: |
        export NGROK_ADDRESS="0.tcp.ap.ngrok.io:15369"  # Replace with the ngrok forwarding address

        # Install sshpass
        sudo apt-get install -y sshpass

        # Establish SSH connection to ngrok tunnel
        sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -p 22 -N -L 2222:$NGROK_ADDRESS ${{ secrets.SSH_USERNAME }}@localhost &

        # Wait for the tunnel to establish
        sleep 5
    - name: Deploy to Device 6th_D
      if: github.ref == 'refs/heads/master'
      run: sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -p 15369 ${{ secrets.SSH_USERNAME }}@0.tcp.ap.ngrok.io 'cd ~/Desktop/config && touch hello.txt'

    - name: VINNCT_A
      if: github.ref == 'refs/heads/tinker'
      run: |
        export NGROK_ADDRESS="0.tcp.ap.ngrok.io:14577"  # Replace with the ngrok forwarding address

        # Install sshpass
        sudo apt-get install -y sshpass

        # Establish SSH connection to ngrok tunnel
        sshpass -p ${{ secrets.TINKER_SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -p 22 -N -L 2222:$NGROK_ADDRESS ${{ secrets.TINKER_SSH_USERNAME }}@localhost &

        # Wait for the tunnel to establish
        sleep 5
    - name: Deploy to Device VINNCT_A
      if: github.ref == 'refs/heads/tinker'
      run: sshpass -p ${{ secrets.TINKER_SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -p 14577 ${{ secrets.SSH_USERNAME }}@0.tcp.ap.ngrok.io 'cd ~/Desktop/config && touch hello.txt'