name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Device 1
      run: ssh -o StrictHostKeyChecking=no -p 15369 pi@0.tcp.ap.ngrok.io 'cd ~/Desktop/config && touch hello.txt'