name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install sshpass
      run: sudo apt-get install -y sshpass
    - name: Checkout code
      uses: actions/checkout@v2
    - name: SSH to ngrok tunnel
        run: |
          export NGROK_ADDRESS="0.tcp.ap.ngrok.io:15369"  # Replace with the ngrok forwarding address

          # Install sshpass
          sudo apt-get install -y sshpass

          # Establish SSH connection to ngrok tunnel
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -p 22 -N -L 2222:$NGROK_ADDRESS ${{ secrets.SSH_USERNAME }}@localhost &

          # Wait for the tunnel to establish
          sleep 5
    - name: Deploy to Device 1
      run: sshpass -p admin12345 ssh -o StrictHostKeyChecking=no -p 15369 pi@0.tcp.ap.ngrok.io 'cd ~/Desktop/config && touch hello.txt'